"""create entries table

Revision ID: 1d56ad46fe63
Revises: 
Create Date: 2026-01-13 23:57:26.895599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d56ad46fe63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.CHAR(32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=False),
    sa.Column('voice_file_id', sa.String(length=255), nullable=True),
    sa.Column('voice_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_entries_user_id_created_at', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index('ix_entries_user_id_created_at')
        batch_op.drop_index(batch_op.f('ix_entries_user_id'))

    op.drop_table('entries')
    # ### end Alembic commands ###
